SOLDIER_HEIGHT = 3
SOLDIER_WIDTH = 2
GRID_HEIGHT = 25
GRID_WIDTH = 50
SCREEN_HEIGHT = 1000
SCREEN_WIDTH = 1500
SQUARE_HEIGHT = SCREEN_HEIGHT / GRID_HEIGHT
SQUARE_WIDTH = SCREEN_WIDTH / GRID_WIDTH
MINE_WIDTH = 3
MINE_HEIGHT = 1
START_MESSAGE = "Welcome To The Flag Game, Have Fun!"

