import pygame

SOLDIER_HEIGHT = 3
SOLDIER_WIDTH = 2
GRID_HEIGHT = 25
GRID_WIDTH = 50
SCREEN_HEIGHT = 1000
SCREEN_WIDTH = 1500
FRAME_HEIGHT = SCREEN_HEIGHT / GRID_HEIGHT
FRAME_WIDTH = SCREEN_WIDTH / GRID_WIDTH
SOLDIER_X_LENGTH = SOLDIER_WIDTH * FRAME_WIDTH
SOLDIER_Y_LENGTH = SOLDIER_HEIGHT * FRAME_HEIGHT

FLAG_HEIGHT = 4
FLAG_WIDTH = 4



MINE_WIDTH = 3
MINE_HEIGHT = 1



GRASS_HEIGHT = 2
GRASS_WIDTH = 2

BACKGROUND_COLOR = (25, 115, 22)

START_MESSAGE = "Welcome To The Flag Game, Have Fun!"
FONT_NAME = "Calibri"
START_FONT_SIZE = int(0.15 * SCREEN_WIDTH)
START_COLOR = (0,0,0)
START_LOCATION = \
    (0.2 * SCREEN_WIDTH, SCREEN_HEIGHT / 2 - (START_FONT_SIZE / 2))


FLAG_IMAGE = pygame.image.load("flag.png").convert()
FLAG_IMAGE = pygame.transform.scale(FLAG_IMAGE, (FLAG_WIDTH * FRAME_WIDTH, FLAG_HEIGHT * FRAME_HEIGHT))

GRASS_IMAGE = pygame.image.load("grass.png").convert()
GRASS_IMAGE = pygame.transform.scale(GRASS_IMAGE, (GRASS_WIDTH * FRAME_WIDTH, GRASS_HEIGHT * FRAME_HEIGHT))

MINE_IMAGE = pygame.image.load("mine.png").convert()
MINE_IMAGE = pygame.transform.scale(MINE_IMAGE, (MINE_WIDTH * FRAME_WIDTH, MINE_HEIGHT * FRAME_HEIGHT))

SOLDIER_IMAGE = pygame.image.load("soldier.png").convert()
SOLDIER_IMAGE = pygame.transform.scale(SOLDIER_IMAGE, (SOLDIER_WIDTH * FRAME_WIDTH, SOLDIER_HEIGHT * FRAME_HEIGHT))

SOLDIER_NIGHT_IMAGE = pygame.image.load("soldier_nigth.png").convert()
SOLDIER_NIGHT_IMAGE= pygame.transform.scale(SOLDIER_NIGHT_IMAGE, (SOLDIER_WIDTH * FRAME_WIDTH, SOLDIER_HEIGHT * FRAME_HEIGHT))

EXPLOSION_IMAGE = pygame.image.load("explosion.png").convert()
EXPLOSION_IMAGE = pygame.transform.scale(EXPLOSION_IMAGE, (3 * FRAME_WIDTH, 2 * FRAME_HEIGHT))
















